name: CI

on: [push]


jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          # os: [ubuntu-latest, macos-latest]
          os: [macos-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: yuanwang-wf
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: yuanwang-wf,nix-community
    - name: Nix build
      run: nix flake update qmk_firmware && nix build .#firmware
    # NOTE Workaround for artifacts and deploy not liking symlinks to
    # read-only paths.
    - name: "Copy artifacts"
      run: "mkdir dist && cp -r result/*  dist/ && chmod +w dist/"
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: firmware.uf2
          path: dist/share/*.uf2
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: keymap.json
          path: dist/share/reiryoku.json
