name: CI

on: [push, pull_request]


jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          trusted-public-keys = yuanwang-wf.cachix.org-1:P/RZ5Iuuuv2MYCNCnAsLfPGmgKMKeTwPaJclkrcwx80= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cachix.org/api/v1/cache/yuanwang-wf https://cache.nixos.org/
    - name: Nix build
      run: nix build .#firmware
    # NOTE Workaround for artifacts and deploy not liking symlinks to
    # read-only paths.
    - name: "Copy artifacts"
      run: "mkdir dist && cp -r result/*  dist/ && chmod +w dist/"
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: firmware.uf2
          path: dist/share/bastardkb_charybdis_3x5_v2_splinky_3_yuanw.uf2
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: keymap.svg
          path: dist/share/reiryoku.svg
