name: CI

on: [push, pull_request]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: yuanwang-wf
        extraPullNames: yuanwang-wf,nix-community
    - name: Nix build
      run: nix build .#firmware --impure
    # NOTE Workaround for artifacts and deploy not liking symlinks to
    # read-only paths.
    - name: "Copy artifacts"
      run: "mkdir dist && cp -r result/*  dist/ && chmod +w dist/"
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: firmware.uf2
          path: dist/share/bastardkb_charybdis_3x5_v2_splinky_3_yuanw.uf2
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
          name: keymap.svg
          path: dist/share/reiryoku.svg
